### ISSUE TITLE
Logo & Touren dropdown vanishes 

### ISSUE THREAD

**Issue by zfhui** [zfhui/Aufbau-Ost-Berlin#16]
It only reappears after a page reload.

**Comment by stho32** [comment]
Dear zfhui, 
I write you about this bug, especially the "dropdown vanishing" that you write about. 
Especially the solution, if you are still interested. 

I tried for some time now, but I'm not good enough with ruby on rails to create you a pull request (or to get it to work locally on my system) - still I might have found the reason, why your dropdown vanishes and how to fix it and I wanted to tell you. 

You only have one big real page load at the time when your page loads up. After that you use ajax requests to load different contents of your pages, which shows up as xhr in the network view of the chrome dev tools. 

Although I cannot really see how and why you do it (well minified js), my guess is, that replacing the html content of the document does not reattach the click-handler for the dropdown which is very probably done by bootstrap3 after page load (~$(document).ready(...)) which cannot occur this time because the page load has already happened. 

So what may the solution be to this problem?

I've actually read some time in the bootstap3 dropdown source code to find, that it uses custom events a lot. And it is well encapsulated to not pollute the global namespace which is bad in this situation since you cannot easily rerun the content. But not as bad as one might probably think.

I attached you the source code of the dropdown.js taken from a download of the bootstrap 3.3.7 source code. 

[dropdown.js.txt](https://github.com/zfhui/Aufbau-Ost-Berlin/files/1464085/dropdown.js.txt)

How the "fix" works:

1. Open http://www.aufbau-ostberlin.de/
2. click a link in the menu, so the content of that other page is loaded differently. As a result the drop-down will stop working.
3. open the dev tools
4. copy the code from the dropdown.js file into the console and execute it. (Its an IIFE.)

As a result you will see that the dropdown starts working again. 
From then on you can navigate around and it will not stop working again. Which I find odd. 
Anyways, putting the code in your ajax loader to be executed at least once the first time it is used will fix your application. 

Feel free to ask me questions or if you need help with the js part. 

Best regards, 
    stho32

**Comment by stho32** [comment]
Hello dear zfhui, 

>From then on you can navigate around and it will not stop working again. Which I find odd.
Having thought over it for a while I'm pretty sure, that the fix does not stop working again because I used the console to inject it. In a real live scenario you'll probably have to call it after every ajax "page" request.

Best regards, 
stho32

**Comment by zfhui** [comment]
Thanks @stho32 for taking your time and suggest fixes! 😃 It's much apprechiated. 🙌

I've just managed to come around this issue and your hint with `$(document).ready` not getting triggered on page load was the correct diagnosis, but the reason was because of the included turbolinks gem in Rails. I updated it to version 5.0 a few months ago and didn't see that it broke some event handeling. 

This is fixed now.
